version: '3.8'
services:
  backend:
    build: ./task-management-backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db

  frontend:
    build: ./task-management-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mcr.microsoft.com/mssql/server  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
